let tabuada = (5*1 )
console.log(tabuada)
tabuada = (5*2)
console.log(tabuada)
tabuada = (5*3)
console.log(tabuada)
tabuada = (5*4)
console.log(tabuada)
tabuada = (5*5)
console.log(tabuada)
tabuada = (5*6)
console.log(tabuada)
tabuada = (5*7)
console.log(tabuada)
tabuada = (5*8)
console.log(tabuada)
tabuada = (5*9)
console.log(tabuada)
tabuada = (5*10)
console.log(tabuada)
